// Pure string templates for the code-api generator.
//
// Each function takes structured input and returns the literal `.ts`
// source emitted to disk. Keeping these pure (no fs, no manifest
// import) makes the generator easy to golden-test and lets the
// generator orchestrate path layout independently.
//
// Stubs are consumed by `tsx` (or `node --import tsx/esm`) in the
// agent's execution environment. They use `.js` import specifiers so
// they work under Node16 ESM resolution after compilation, and tsx
// resolves them transparently for direct .ts execution.

import {
  extractPathParams,
  type Operation,
  type ParamSpec,
} from "../core/manifest.js";

// Marker placed at the top of every generated file. Tests assert on
// it; humans see it and know not to hand-edit.
export const GENERATED_BANNER = `// AUTO-GENERATED by jira-mcp Layer 3 code-api generator. Do not edit by hand.\n// Source of truth: src/core/operations.ts (manifest entries).`;

// --- Name helpers ------------------------------------------------------

// "issue.get" → { category: "issue", verb: "get" }. The manifest's
// dot-separated naming is load-bearing here: the generator splits on
// the *first* dot only, so a hypothetical "issue.foo.bar" would land
// at issue/foo.bar.ts (we don't have any such names today).
export function splitOperationName(opName: string): {
  category: string;
  verb: string;
} {
  const dot = opName.indexOf(".");
  if (dot < 0) {
    throw new Error(
      `Operation name must be 'category.verb', got: ${opName}`,
    );
  }
  return {
    category: opName.slice(0, dot),
    verb: opName.slice(dot + 1),
  };
}

// JS reserved words (and a couple of soft-reserved names) that would
// be syntax errors as parameter names. None of the current Jira params
// hit these, but we sanitize defensively so a future manifest entry
// can't break codegen silently.
const RESERVED = new Set([
  "default",
  "delete",
  "function",
  "class",
  "const",
  "let",
  "var",
  "return",
  "import",
  "export",
  "new",
  "typeof",
  "instanceof",
  "in",
  "of",
  "this",
  "super",
  "void",
  "null",
  "true",
  "false",
]);

export function safeIdentifier(name: string): string {
  if (RESERVED.has(name)) return `${name}_`;
  return name;
}

// --- Per-operation rendering ------------------------------------------

// Map a ParamSpec to a TS type literal. The manifest is stringly
// typed by design (PR #6) — we only know role + required, not the
// underlying TS shape. So path/query params are `string | number`
// (most common scalar shapes Jira accepts in URLs) and body params
// are `unknown` (callers pass arbitrary JSON-shaped values).
function paramType(spec: ParamSpec): string {
  switch (spec.role) {
    case "path":
      return "string | number";
    case "query":
      // Arrays are flattened to comma-separated strings by the
      // dispatcher (see manifest.ts), so accept either shape here.
      return "string | number | boolean | Array<string | number>";
    case "body":
      return "unknown";
  }
}

export interface RenderedStub {
  // Path relative to the generator's outDir, using POSIX separators
  // (the generator translates to OS-native on write).
  relativePath: string;
  contents: string;
}

// Emit a single operation's stub. One file per operation, exporting
// one function whose name matches the verb portion of the operation
// name. Uses an args object (rather than positional params) so the
// signature stays stable as the manifest evolves.
export function renderStub(op: Operation): RenderedStub {
  const { category, verb } = splitOperationName(op.name);
  const fnName = safeIdentifier(verb);

  // Path params are always required even if the manifest doesn't say
  // so explicitly — a missing path param produces a runtime error in
  // interpolatePath. Mark them required in the TS type to surface
  // that constraint at edit time.
  const pathNames = new Set(extractPathParams(op.pathTemplate));

  // Sort: required first (to match how callers usually write object
  // literals), then by role (path → query → body), then by name for
  // deterministic output across regenerations.
  const sorted = [...op.params].sort((a, b) => {
    const reqA = a.required || pathNames.has(a.name) ? 0 : 1;
    const reqB = b.required || pathNames.has(b.name) ? 0 : 1;
    if (reqA !== reqB) return reqA - reqB;
    const roleOrder = { path: 0, query: 1, body: 2 } as const;
    if (roleOrder[a.role] !== roleOrder[b.role]) {
      return roleOrder[a.role] - roleOrder[b.role];
    }
    return a.name.localeCompare(b.name);
  });

  const fields = sorted.map((p) => {
    const required = p.required || pathNames.has(p.name);
    const optional = required ? "" : "?";
    const desc = p.description ? ` // ${p.role}: ${p.description}` : ` // ${p.role}`;
    return `  ${safeIdentifier(p.name)}${optional}: ${paramType(p)};${desc}`;
  });

  // Args interface name: e.g. "issue.get" → "IssueGetArgs".
  const argsTypeName = `${capitalize(category)}${capitalize(verb)}Args`;

  const hasParams = fields.length > 0;
  const argsBlock = hasParams
    ? `export interface ${argsTypeName} {\n${fields.join("\n")}\n}\n\n`
    : "";

  const argsParam = hasParams ? `args: ${argsTypeName}` : "args: Record<string, never> = {}";
  const passArgs = hasParams ? "args" : "{}";

  const trimNote = op.trim
    ? `\n * Response is trimmed via the '${op.trim}' projection — see src/core/trim.ts.`
    : "";
  const agileNote = op.isAgile ? "\n * (Agile API endpoint.)" : "";

  const body =
    `${GENERATED_BANNER}\n\n` +
    `import { invoke } from "../_client.js";\n` +
    `import type { Ref } from "../types.js";\n\n` +
    argsBlock +
    `/**\n` +
    ` * ${op.description}\n` +
    ` *\n` +
    ` * Operation: ${op.name} (${op.verb} ${op.pathTemplate})${agileNote}${trimNote}\n` +
    ` */\n` +
    `export function ${fnName}(${argsParam}): Promise<Ref<unknown>> {\n` +
    `  return invoke(${JSON.stringify(op.name)}, ${passArgs});\n` +
    `}\n`;

  return {
    relativePath: `${category}/${verb}.ts`,
    contents: body,
  };
}

function capitalize(s: string): string {
  return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1);
}

// --- Per-category index ------------------------------------------------

// Re-exports every stub in a category as a named export, so callers
// can write either:
//   import { get } from ".../api/issue/get.js"
//   import * as issue from ".../api/issue/index.js"; issue.get(...)
export function renderCategoryIndex(
  category: string,
  operations: Operation[],
): string {
  const lines = operations
    .map((op) => splitOperationName(op.name).verb)
    .sort()
    .map((verb) => `export { ${safeIdentifier(verb)} } from "./${verb}.js";`);
  return `${GENERATED_BANNER}\n\n${lines.join("\n")}\n`;
}

// --- Top-level index ---------------------------------------------------

// Emits namespace re-exports keyed by category, so the agent can
// import the whole API surface in one line:
//   import * as jira from ".../api/index.js"
//   await jira.issue.get({ issueIdOrKey: "PROJ-1" })
export function renderRootIndex(categories: string[]): string {
  const lines = [...categories]
    .sort()
    .map((cat) => `export * as ${safeIdentifier(cat)} from "./${cat}/index.js";`);
  return `${GENERATED_BANNER}\n\n${lines.join("\n")}\n`;
}

// --- Static support files ----------------------------------------------

// types.ts — re-exports the Ref shape from the runtime project so
// the stubs don't carry a copy. Generated stubs live outside the
// repo root; they import via absolute path resolved at generate
// time (see generator.ts which writes the resolved path in).
export function renderTypesFile(refsImportPath: string): string {
  return (
    `${GENERATED_BANNER}\n\n` +
    `// Re-exports the Ref<T> shape from the running jira-mcp build,\n` +
    `// so generated stubs can stay independent of the user's tsconfig\n` +
    `// while still typing responses correctly.\n` +
    `export type { Ref, SandboxResult } from ${JSON.stringify(refsImportPath)};\n`
  );
}

// _client.ts — connects to the jira-mcp bridge over a local socket
// and forwards each `invoke()` call as a single ND-JSON request.
//
// Wire format is documented in src/codeapi/bridge.ts. The client
// opens a fresh connection per call: simpler than pooling, and each
// call's latency is dominated by the Jira HTTP round-trip on the
// server side, not the local socket setup.
//
// Address discovery: reads `JIRA_MCP_SOCKET` from the environment.
// PR #10 will set this when the MCP server spawns the agent's
// execution context. Two formats supported:
//
//   - "/abs/path/to/ipc.sock"      — Unix domain socket (POSIX)
//   - "tcp:127.0.0.1:54321"        — loopback TCP (Windows)
export function renderClientFile(): string {
  return (
    `${GENERATED_BANNER}\n\n` +
    `// Bridge client for the jira-mcp Layer 3 code-api.\n` +
    `// Connects to the bridge server over a local socket per call.\n\n` +
    `import { connect, type Socket } from "node:net";\n` +
    `import type { Ref } from "./types.js";\n\n` +
    `const SOCKET_ENV = "JIRA_MCP_SOCKET";\n\n` +
    `interface BridgeOk { id: string; result: Ref<unknown> }\n` +
    `interface BridgeErr { id: string; error: { name: string; message: string } }\n` +
    `type BridgeResponse = BridgeOk | BridgeErr;\n\n` +
    `function resolveSocket(): { path?: string; host?: string; port?: number } {\n` +
    `  const raw = process.env[SOCKET_ENV];\n` +
    `  if (!raw) {\n` +
    `    throw new Error(\n` +
    `      \`jira-mcp bridge address not set: \${SOCKET_ENV} env var missing. \` +\n` +
    `        \`Was this stub called outside the MCP server's execution context?\`,\n` +
    `    );\n` +
    `  }\n` +
    `  if (raw.startsWith("tcp:")) {\n` +
    `    const lastColon = raw.lastIndexOf(":");\n` +
    `    const host = raw.slice(4, lastColon);\n` +
    `    const port = Number(raw.slice(lastColon + 1));\n` +
    `    if (!host || !Number.isFinite(port)) {\n` +
    `      throw new Error(\`Malformed \${SOCKET_ENV}: \${raw}\`);\n` +
    `    }\n` +
    `    return { host, port };\n` +
    `  }\n` +
    `  return { path: raw };\n` +
    `}\n\n` +
    `let nextId = 0;\n\n` +
    `export function invoke(\n` +
    `  operation: string,\n` +
    `  args: Record<string, unknown>,\n` +
    `): Promise<Ref<unknown>> {\n` +
    `  const id = String(++nextId);\n` +
    `  return new Promise<Ref<unknown>>((resolve, reject) => {\n` +
    `    let target: { path?: string; host?: string; port?: number };\n` +
    `    try {\n` +
    `      target = resolveSocket();\n` +
    `    } catch (err) {\n` +
    `      reject(err);\n` +
    `      return;\n` +
    `    }\n` +
    `    const socket: Socket = connect(target as never);\n` +
    `    socket.setEncoding("utf8");\n` +
    `    let buffer = "";\n` +
    `    let settled = false;\n` +
    `    const settle = (fn: () => void) => {\n` +
    `      if (settled) return;\n` +
    `      settled = true;\n` +
    `      socket.end();\n` +
    `      fn();\n` +
    `    };\n` +
    `    socket.on("connect", () => {\n` +
    `      socket.write(\n` +
    `        JSON.stringify({ id, method: "invoke", params: { operation, args } }) + "\\n",\n` +
    `      );\n` +
    `    });\n` +
    `    socket.on("data", (chunk: string) => {\n` +
    `      buffer += chunk;\n` +
    `      const nl = buffer.indexOf("\\n");\n` +
    `      if (nl < 0) return;\n` +
    `      const line = buffer.slice(0, nl);\n` +
    `      let resp: BridgeResponse;\n` +
    `      try {\n` +
    `        resp = JSON.parse(line);\n` +
    `      } catch (err) {\n` +
    `        settle(() => reject(err));\n` +
    `        return;\n` +
    `      }\n` +
    `      if ("error" in resp) {\n` +
    `        const e = new Error(resp.error.message);\n` +
    `        e.name = resp.error.name;\n` +
    `        settle(() => reject(e));\n` +
    `      } else {\n` +
    `        settle(() => resolve(resp.result));\n` +
    `      }\n` +
    `    });\n` +
    `    socket.on("error", (err: Error) => settle(() => reject(err)));\n` +
    `    socket.on("close", () => {\n` +
    `      if (!settled) {\n` +
    `        settle(() =>\n` +
    `          reject(new Error("jira-mcp bridge closed before responding")),\n` +
    `        );\n` +
    `      }\n` +
    `    });\n` +
    `  });\n` +
    `}\n`
  );
}
