// Pure string templates for the code-api generator.
//
// Each function takes structured input and returns the literal `.ts`
// source emitted to disk. Keeping these pure (no fs, no manifest
// import) makes the generator easy to golden-test and lets the
// generator orchestrate path layout independently.
//
// Stubs are consumed by `tsx` (or `node --import tsx/esm`) in the
// agent's execution environment. They use `.js` import specifiers so
// they work under Node16 ESM resolution after compilation, and tsx
// resolves them transparently for direct .ts execution.

import {
  extractPathParams,
  type Operation,
  type ParamSpec,
} from "../core/manifest.js";

// Marker placed at the top of every generated file. Tests assert on
// it; humans see it and know not to hand-edit.
export const GENERATED_BANNER = `// AUTO-GENERATED by jira-mcp Layer 3 code-api generator. Do not edit by hand.\n// Source of truth: src/core/operations.ts (manifest entries).`;

// --- Name helpers ------------------------------------------------------

// "issue.get" → { category: "issue", verb: "get" }. The manifest's
// dot-separated naming is load-bearing here: the generator splits on
// the *first* dot only, so a hypothetical "issue.foo.bar" would land
// at issue/foo.bar.ts (we don't have any such names today).
export function splitOperationName(opName: string): {
  category: string;
  verb: string;
} {
  const dot = opName.indexOf(".");
  if (dot < 0) {
    throw new Error(
      `Operation name must be 'category.verb', got: ${opName}`,
    );
  }
  return {
    category: opName.slice(0, dot),
    verb: opName.slice(dot + 1),
  };
}

// JS reserved words (and a couple of soft-reserved names) that would
// be syntax errors as parameter names. None of the current Jira params
// hit these, but we sanitize defensively so a future manifest entry
// can't break codegen silently.
const RESERVED = new Set([
  "default",
  "delete",
  "function",
  "class",
  "const",
  "let",
  "var",
  "return",
  "import",
  "export",
  "new",
  "typeof",
  "instanceof",
  "in",
  "of",
  "this",
  "super",
  "void",
  "null",
  "true",
  "false",
]);

export function safeIdentifier(name: string): string {
  if (RESERVED.has(name)) return `${name}_`;
  return name;
}

// --- Per-operation rendering ------------------------------------------

// Map a ParamSpec to a TS type literal. The manifest is stringly
// typed by design (PR #6) — we only know role + required, not the
// underlying TS shape. So path/query params are `string | number`
// (most common scalar shapes Jira accepts in URLs) and body params
// are `unknown` (callers pass arbitrary JSON-shaped values).
function paramType(spec: ParamSpec): string {
  switch (spec.role) {
    case "path":
      return "string | number";
    case "query":
      // Arrays are flattened to comma-separated strings by the
      // dispatcher (see manifest.ts), so accept either shape here.
      return "string | number | boolean | Array<string | number>";
    case "body":
      return "unknown";
  }
}

export interface RenderedStub {
  // Path relative to the generator's outDir, using POSIX separators
  // (the generator translates to OS-native on write).
  relativePath: string;
  contents: string;
}

// Emit a single operation's stub. One file per operation, exporting
// one function whose name matches the verb portion of the operation
// name. Uses an args object (rather than positional params) so the
// signature stays stable as the manifest evolves.
export function renderStub(op: Operation): RenderedStub {
  const { category, verb } = splitOperationName(op.name);
  const fnName = safeIdentifier(verb);

  // Path params are always required even if the manifest doesn't say
  // so explicitly — a missing path param produces a runtime error in
  // interpolatePath. Mark them required in the TS type to surface
  // that constraint at edit time.
  const pathNames = new Set(extractPathParams(op.pathTemplate));

  // Sort: required first (to match how callers usually write object
  // literals), then by role (path → query → body), then by name for
  // deterministic output across regenerations.
  const sorted = [...op.params].sort((a, b) => {
    const reqA = a.required || pathNames.has(a.name) ? 0 : 1;
    const reqB = b.required || pathNames.has(b.name) ? 0 : 1;
    if (reqA !== reqB) return reqA - reqB;
    const roleOrder = { path: 0, query: 1, body: 2 } as const;
    if (roleOrder[a.role] !== roleOrder[b.role]) {
      return roleOrder[a.role] - roleOrder[b.role];
    }
    return a.name.localeCompare(b.name);
  });

  const fields = sorted.map((p) => {
    const required = p.required || pathNames.has(p.name);
    const optional = required ? "" : "?";
    const desc = p.description ? ` // ${p.role}: ${p.description}` : ` // ${p.role}`;
    return `  ${safeIdentifier(p.name)}${optional}: ${paramType(p)};${desc}`;
  });

  // Args interface name: e.g. "issue.get" → "IssueGetArgs".
  const argsTypeName = `${capitalize(category)}${capitalize(verb)}Args`;

  const hasParams = fields.length > 0;
  const argsBlock = hasParams
    ? `export interface ${argsTypeName} {\n${fields.join("\n")}\n}\n\n`
    : "";

  const argsParam = hasParams ? `args: ${argsTypeName}` : "args: Record<string, never> = {}";
  const passArgs = hasParams ? "args" : "{}";

  const trimNote = op.trim
    ? `\n * Response is trimmed via the '${op.trim}' projection — see src/core/trim.ts.`
    : "";
  const agileNote = op.isAgile ? "\n * (Agile API endpoint.)" : "";

  const body =
    `${GENERATED_BANNER}\n\n` +
    `import { invoke } from "../_client.js";\n` +
    `import type { Ref } from "../types.js";\n\n` +
    argsBlock +
    `/**\n` +
    ` * ${op.description}\n` +
    ` *\n` +
    ` * Operation: ${op.name} (${op.verb} ${op.pathTemplate})${agileNote}${trimNote}\n` +
    ` */\n` +
    `export function ${fnName}(${argsParam}): Promise<Ref<unknown>> {\n` +
    `  return invoke(${JSON.stringify(op.name)}, ${passArgs});\n` +
    `}\n`;

  return {
    relativePath: `${category}/${verb}.ts`,
    contents: body,
  };
}

function capitalize(s: string): string {
  return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1);
}

// --- Per-category index ------------------------------------------------

// Re-exports every stub in a category as a named export, so callers
// can write either:
//   import { get } from ".../api/issue/get.js"
//   import * as issue from ".../api/issue/index.js"; issue.get(...)
export function renderCategoryIndex(
  category: string,
  operations: Operation[],
): string {
  const lines = operations
    .map((op) => splitOperationName(op.name).verb)
    .sort()
    .map((verb) => `export { ${safeIdentifier(verb)} } from "./${verb}.js";`);
  return `${GENERATED_BANNER}\n\n${lines.join("\n")}\n`;
}

// --- Top-level index ---------------------------------------------------

// Emits namespace re-exports keyed by category, so the agent can
// import the whole API surface in one line:
//   import * as jira from ".../api/index.js"
//   await jira.issue.get({ issueIdOrKey: "PROJ-1" })
export function renderRootIndex(categories: string[]): string {
  const lines = [...categories]
    .sort()
    .map((cat) => `export * as ${safeIdentifier(cat)} from "./${cat}/index.js";`);
  return `${GENERATED_BANNER}\n\n${lines.join("\n")}\n`;
}

// --- Static support files ----------------------------------------------

// types.ts — re-exports the Ref shape from the runtime project so
// the stubs don't carry a copy. Generated stubs live outside the
// repo root; they import via absolute path resolved at generate
// time (see generator.ts which writes the resolved path in).
export function renderTypesFile(refsImportPath: string): string {
  return (
    `${GENERATED_BANNER}\n\n` +
    `// Re-exports the Ref<T> shape from the running jira-mcp build,\n` +
    `// so generated stubs can stay independent of the user's tsconfig\n` +
    `// while still typing responses correctly.\n` +
    `export type { Ref, SandboxResult } from ${JSON.stringify(refsImportPath)};\n`
  );
}

// _client.ts — placeholder bridge. PR #9 wires this to a Unix
// socket / loopback TCP. For now it throws so a stub used in
// isolation surfaces a clear error rather than silently hanging.
export function renderClientFile(): string {
  return (
    `${GENERATED_BANNER}\n\n` +
    `// Bridge to the running jira-mcp server. The real implementation\n` +
    `// (JSON-RPC over Unix socket or loopback TCP) lands in PR #9.\n` +
    `// Until then, calls fail loudly so misuse is obvious.\n\n` +
    `import type { Ref } from "./types.js";\n\n` +
    `export async function invoke(\n` +
    `  operationName: string,\n` +
    `  _args: Record<string, unknown>,\n` +
    `): Promise<Ref<unknown>> {\n` +
    `  throw new Error(\n` +
    `    \`jira-mcp code-api bridge not implemented yet (operation: \${operationName}). \` +\n` +
    `      \`Wired in PR #9 — until then, use the classic MCP tools.\`,\n` +
    `  );\n` +
    `}\n`
  );
}
